//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanelliDinamikCV_App.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainings
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string SubTitle2 { get; set; }
        public string Gno { get; set; }
        public string Date { get; set; }
    }
}
